name: Publish Docker image
on:
  push:
    branches: [ main ]
jobs:
  publish_to_dev:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up Python 3.9.5
        uses: actions/setup-python@v1
        with:
          python-version: "3.9.5"
      
      - name: Python Pylin GitHub Action
        uses: fylein/python-pylint-github-action@v1
        with:
          args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc *
      
      - name: Tag
        id: autotagger
        uses: butlerlogic/action-autotag@1.1.2
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          strategy: docker
          tag_prefix: "v"


      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        if: steps.autotagger.outputs.version != ''
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: guillermoadc/cribl-filemanager:${{ steps.autotagger.outputs.version }}

      - name: Deploy app
        if: steps.autotagger.outputs.version != ''
        uses: appleboy/ssh-action@master
        env:
          APP_VERSION: ${{ steps.autotagger.outputs.version }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          envs: APP_VERSION
          script: |
            echo $APP_VERSION
            CONTAINER_LIST=$(sudo docker ps)
            if [[ $CONTAINER_LIST == *"cribl-filemanager"* ]]; then 
              sudo docker rm -f cribl-filemanager 
            fi
            sudo docker pull guillermoadc/cribl-filemanager:$APP_VERSION
            sudo docker run -d -p 5000:5000 --name cribl-filemanager guillermoadc/cribl-filemanager:$APP_VERSION
