name: Publish Docker image
on:
  push:
    branches: [ main ]
jobs:
  publish:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up Python 3.9.5
        uses: actions/setup-python@v1
        with:
          python-version: "3.9.5"
      
      - name: Python Pylin GitHub Action
        uses: fylein/python-pylint-github-action@v1
        with:
          args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc *
      
      - name: Tag
        id: autotagger
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          strategy: docker
          tag_prefix: "v"


      - name: Log in to Docker Hub
        
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        if: steps.autotagger.outputs.tagname != ''
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: guillermoadc/cribl-filemanager:${{ steps.autotagger.outputs.tagname }}

      # - name: Copy App
      #   uses: nogsantos/scp-deploy@master
      #   with:
      #     src: ./*
      #     host: ${{ secrets.SERVER_IP }}
      #     remote: /home/ec2-user
      #     port: 22
      #     user: ec2-user
      #     key: ${{ secrets.SSH_KEY }}
      

      # - name: Deploy app
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_IP }}
      #     username: ec2-user
      #     key: ${{ secrets.SSH_KEY }}
      #     port: 22
      #     script: |
      #       make remove
      #       make build
      #       make up